const vocabularyWords = [
  // Numbers 1-20
  { id: 'num_1', english: 'one', french: 'un', italian: 'uno', category: 'numbers', imagePrompt: 'single object, number 1, colorful counting illustration for children' },
  { id: 'num_2', english: 'two', french: 'deux', italian: 'due', category: 'numbers', imagePrompt: 'two objects, number 2, colorful counting illustration for children' },
  { id: 'num_3', english: 'three', french: 'trois', italian: 'tre', category: 'numbers', imagePrompt: 'three objects, number 3, colorful counting illustration for children' },
  { id: 'num_4', english: 'four', french: 'quatre', italian: 'quattro', category: 'numbers', imagePrompt: 'four objects, number 4, colorful counting illustration for children' },
  { id: 'num_5', english: 'five', french: 'cinq', italian: 'cinque', category: 'numbers', imagePrompt: 'five objects, number 5, colorful counting illustration for children' },
  { id: 'num_6', english: 'six', french: 'six', italian: 'sei', category: 'numbers', imagePrompt: 'six objects, number 6, colorful counting illustration for children' },
  { id: 'num_7', english: 'seven', french: 'sept', italian: 'sette', category: 'numbers', imagePrompt: 'seven objects, number 7, colorful counting illustration for children' },
  { id: 'num_8', english: 'eight', french: 'huit', italian: 'otto', category: 'numbers', imagePrompt: 'eight objects, number 8, colorful counting illustration for children' },
  { id: 'num_9', english: 'nine', french: 'neuf', italian: 'nove', category: 'numbers', imagePrompt: 'nine objects, number 9, colorful counting illustration for children' },
  { id: 'num_10', english: 'ten', french: 'dix', italian: 'dieci', category: 'numbers', imagePrompt: 'ten objects, number 10, colorful counting illustration for children' },
  { id: 'num_11', english: 'eleven', french: 'onze', italian: 'undici', category: 'numbers', imagePrompt: 'eleven objects, number 11, colorful counting illustration for children' },
  { id: 'num_12', english: 'twelve', french: 'douze', italian: 'dodici', category: 'numbers', imagePrompt: 'twelve objects, number 12, colorful counting illustration for children' },
  { id: 'num_13', english: 'thirteen', french: 'treize', italian: 'tredici', category: 'numbers', imagePrompt: 'thirteen objects, number 13, colorful counting illustration for children' },
  { id: 'num_14', english: 'fourteen', french: 'quatorze', italian: 'quattordici', category: 'numbers', imagePrompt: 'fourteen objects, number 14, colorful counting illustration for children' },
  { id: 'num_15', english: 'fifteen', french: 'quinze', italian: 'quindici', category: 'numbers', imagePrompt: 'fifteen objects, number 15, colorful counting illustration for children' },
  { id: 'num_16', english: 'sixteen', french: 'seize', italian: 'sedici', category: 'numbers', imagePrompt: 'sixteen objects, number 16, colorful counting illustration for children' },
  { id: 'num_17', english: 'seventeen', french: 'dix-sept', italian: 'diciassette', category: 'numbers', imagePrompt: 'seventeen objects, number 17, colorful counting illustration for children' },
  { id: 'num_18', english: 'eighteen', french: 'dix-huit', italian: 'diciotto', category: 'numbers', imagePrompt: 'eighteen objects, number 18, colorful counting illustration for children' },
  { id: 'num_19', english: 'nineteen', french: 'dix-neuf', italian: 'diciannove', category: 'numbers', imagePrompt: 'nineteen objects, number 19, colorful counting illustration for children' },
  { id: 'num_20', english: 'twenty', french: 'vingt', italian: 'venti', category: 'numbers', imagePrompt: 'twenty objects, number 20, colorful counting illustration for children' },

  // Greetings & Politeness
  { id: 'greet_1', english: 'hello', french: 'bonjour', italian: 'ciao', category: 'greetings', imagePrompt: 'friendly waving hand, greeting gesture, warm welcome illustration for children' },
  { id: 'greet_2', english: 'goodbye', french: 'au revoir', italian: 'arrivederci', category: 'greetings', imagePrompt: 'waving goodbye, farewell gesture, friendly parting illustration for children' },
  { id: 'greet_3', english: 'please', french: 's\'il vous plaît', italian: 'per favore', category: 'greetings', imagePrompt: 'polite gesture, asking nicely, please sign illustration for children' },
  { id: 'greet_4', english: 'thank you', french: 'merci', italian: 'grazie', category: 'greetings', imagePrompt: 'thankful gesture, gratitude, thank you illustration for children' },
  { id: 'greet_5', english: 'sorry', french: 'pardon', italian: 'scusa', category: 'greetings', imagePrompt: 'apologetic gesture, sorry expression, apology illustration for children' },
  { id: 'greet_6', english: 'good morning', french: 'bon matin', italian: 'buongiorno', category: 'greetings', imagePrompt: 'sunrise, morning greeting, cheerful morning illustration for children' },
  { id: 'greet_7', english: 'good night', french: 'bonne nuit', italian: 'buonanotte', category: 'greetings', imagePrompt: 'moon and stars, bedtime, good night illustration for children' },
  { id: 'greet_8', english: 'yes', french: 'oui', italian: 'sì', category: 'greetings', imagePrompt: 'thumbs up, yes gesture, positive affirmation illustration for children' },
  { id: 'greet_9', english: 'no', french: 'non', italian: 'no', category: 'greetings', imagePrompt: 'shaking head, no gesture, negative response illustration for children' },
  { id: 'greet_10', english: 'excuse me', french: 'excusez-moi', italian: 'scusi', category: 'greetings', imagePrompt: 'polite interruption, excuse me gesture, attention seeking illustration for children' },

  // Family Members
  { id: 'fam_1', english: 'mother', french: 'mère', italian: 'madre', category: 'family', imagePrompt: 'caring mother figure, mom with heart, maternal illustration for children' },
  { id: 'fam_2', english: 'father', french: 'père', italian: 'padre', category: 'family', imagePrompt: 'loving father figure, dad with smile, paternal illustration for children' },
  { id: 'fam_3', english: 'sister', french: 'sœur', italian: 'sorella', category: 'family', imagePrompt: 'young girl sibling, sister with pigtails, sisterly illustration for children' },
  { id: 'fam_4', english: 'brother', french: 'frère', italian: 'fratello', category: 'family', imagePrompt: 'young boy sibling, brother with cap, brotherly illustration for children' },
  { id: 'fam_5', english: 'grandmother', french: 'grand-mère', italian: 'nonna', category: 'family', imagePrompt: 'elderly woman with glasses, grandma knitting, grandmother illustration for children' },
  { id: 'fam_6', english: 'grandfather', french: 'grand-père', italian: 'nonno', category: 'family', imagePrompt: 'elderly man with beard, grandpa with cane, grandfather illustration for children' },
  { id: 'fam_7', english: 'aunt', french: 'tante', italian: 'zia', category: 'family', imagePrompt: 'friendly adult woman, aunt with gift, auntie illustration for children' },
  { id: 'fam_8', english: 'uncle', french: 'oncle', italian: 'zio', category: 'family', imagePrompt: 'friendly adult man, uncle with hat, uncle illustration for children' },
  { id: 'fam_9', english: 'cousin', french: 'cousin', italian: 'cugino', category: 'family', imagePrompt: 'child playing, cousin friend, relative child illustration' },
  { id: 'fam_10', english: 'baby', french: 'bébé', italian: 'bambino', category: 'family', imagePrompt: 'cute baby with pacifier, infant crawling, baby illustration for children' },
  { id: 'fam_11', english: 'family', french: 'famille', italian: 'famiglia', category: 'family', imagePrompt: 'happy family group, parents and children together, family portrait illustration' },
  { id: 'fam_12', english: 'parents', french: 'parents', italian: 'genitori', category: 'family', imagePrompt: 'mother and father together, parent couple, parental illustration for children' },

  // People
  { id: 'ppl_1', english: 'boy', french: 'garçon', italian: 'ragazzo', category: 'people', imagePrompt: 'young boy with backpack, male child, boy illustration for children' },
  { id: 'ppl_2', english: 'girl', french: 'fille', italian: 'ragazza', category: 'people', imagePrompt: 'young girl with dress, female child, girl illustration for children' },
  { id: 'ppl_3', english: 'man', french: 'homme', italian: 'uomo', category: 'people', imagePrompt: 'adult male figure, man in suit, gentleman illustration for children' },
  { id: 'ppl_4', english: 'woman', french: 'femme', italian: 'donna', category: 'people', imagePrompt: 'adult female figure, woman in dress, lady illustration for children' },
  { id: 'ppl_5', english: 'friend', french: 'ami', italian: 'amico', category: 'people', imagePrompt: 'two children playing, friendship, best friends illustration for children' },
  { id: 'ppl_6', english: 'teacher', french: 'professeur', italian: 'insegnante', category: 'people', imagePrompt: 'teacher at blackboard, educator with book, teacher illustration for children' },
  { id: 'ppl_7', english: 'doctor', french: 'docteur', italian: 'dottore', category: 'people', imagePrompt: 'doctor with stethoscope, medical professional, physician illustration for children' },
  { id: 'ppl_8', english: 'child', french: 'enfant', italian: 'bambino', category: 'people', imagePrompt: 'happy child playing, kid with toy, child illustration' },
  { id: 'ppl_9', english: 'person', french: 'personne', italian: 'persona', category: 'people', imagePrompt: 'generic human figure, person silhouette, individual illustration for children' },
  { id: 'ppl_10', english: 'neighbor', french: 'voisin', italian: 'vicino', category: 'people', imagePrompt: 'friendly neighbor waving, person next door, neighbor illustration for children' },

  // Animals
  { id: 'ani_1', english: 'dog', french: 'chien', italian: 'cane', category: 'animals', imagePrompt: 'friendly dog wagging tail, puppy playing, dog illustration for children' },
  { id: 'ani_2', english: 'cat', french: 'chat', italian: 'gatto', category: 'animals', imagePrompt: 'cute cat with whiskers, kitten playing, cat illustration for children' },
  { id: 'ani_3', english: 'bird', french: 'oiseau', italian: 'uccello', category: 'animals', imagePrompt: 'colorful bird singing, bird on branch, bird illustration for children' },
  { id: 'ani_4', english: 'fish', french: 'poisson', italian: 'pesce', category: 'animals', imagePrompt: 'goldfish swimming, fish in bowl, fish illustration for children' },
  { id: 'ani_5', english: 'rabbit', french: 'lapin', italian: 'coniglio', category: 'animals', imagePrompt: 'bunny with long ears, rabbit hopping, bunny illustration for children' },
  { id: 'ani_6', english: 'horse', french: 'cheval', italian: 'cavallo', category: 'animals', imagePrompt: 'horse galloping, pony in field, horse illustration for children' },
  { id: 'ani_7', english: 'cow', french: 'vache', italian: 'mucca', category: 'animals', imagePrompt: 'cow with spots, cow in pasture, cow illustration for children' },
  { id: 'ani_8', english: 'pig', french: 'cochon', italian: 'maiale', category: 'animals', imagePrompt: 'pink pig with curly tail, pig in mud, pig illustration for children' },
  { id: 'ani_9', english: 'sheep', french: 'mouton', italian: 'pecora', category: 'animals', imagePrompt: 'fluffy white sheep, lamb in field, sheep illustration for children' },
  { id: 'ani_10', english: 'chicken', french: 'poulet', italian: 'pollo', category: 'animals', imagePrompt: 'hen with chicks, rooster crowing, chicken illustration for children' },
  { id: 'ani_11', english: 'duck', french: 'canard', italian: 'anatra', category: 'animals', imagePrompt: 'duck swimming, duck with ducklings, duck illustration for children' },
  { id: 'ani_12', english: 'mouse', french: 'souris', italian: 'topo', category: 'animals', imagePrompt: 'small mouse with cheese, mouse with whiskers, mouse illustration for children' },
  { id: 'ani_13', english: 'elephant', french: 'éléphant', italian: 'elefante', category: 'animals', imagePrompt: 'elephant with trunk, baby elephant, elephant illustration for children' },
  { id: 'ani_14', english: 'lion', french: 'lion', italian: 'leone', category: 'animals', imagePrompt: 'lion with mane, king of jungle, lion illustration for children' },
  { id: 'ani_15', english: 'tiger', french: 'tigre', italian: 'tigre', category: 'animals', imagePrompt: 'tiger with stripes, jungle tiger, tiger illustration for children' },
  { id: 'ani_16', english: 'bear', french: 'ours', italian: 'orso', category: 'animals', imagePrompt: 'brown bear standing, teddy bear, bear illustration for children' },
  { id: 'ani_17', english: 'monkey', french: 'singe', italian: 'scimmia', category: 'animals', imagePrompt: 'monkey swinging, playful monkey, monkey illustration for children' },
  { id: 'ani_18', english: 'giraffe', french: 'girafe', italian: 'giraffa', category: 'animals', imagePrompt: 'tall giraffe with spots, long neck giraffe, giraffe illustration for children' },
  { id: 'ani_19', english: 'zebra', french: 'zèbre', italian: 'zebra', category: 'animals', imagePrompt: 'zebra with stripes, black and white zebra, zebra illustration for children' },
  { id: 'ani_20', english: 'butterfly', french: 'papillon', italian: 'farfalla', category: 'animals', imagePrompt: 'colorful butterfly flying, butterfly on flower, butterfly illustration for children' },
  { id: 'ani_21', english: 'bee', french: 'abeille', italian: 'ape', category: 'animals', imagePrompt: 'bee with honey, buzzing bee, bee illustration for children' },
  { id: 'ani_22', english: 'spider', french: 'araignée', italian: 'ragno', category: 'animals', imagePrompt: 'spider on web, friendly spider, spider illustration for children' },
  { id: 'ani_23', english: 'snake', french: 'serpent', italian: 'serpente', category: 'animals', imagePrompt: 'coiled snake, green snake, snake illustration for children' },
  { id: 'ani_24', english: 'turtle', french: 'tortue', italian: 'tartaruga', category: 'animals', imagePrompt: 'turtle with shell, slow turtle, turtle illustration for children' },
  { id: 'ani_25', english: 'frog', french: 'grenouille', italian: 'rana', category: 'animals', imagePrompt: 'green frog on lily pad, jumping frog, frog illustration for children' },

  // Food & Drinks
  { id: 'food_1', english: 'apple', french: 'pomme', italian: 'mela', category: 'food', imagePrompt: 'red apple with leaf, shiny apple, apple illustration for children' },
  { id: 'food_2', english: 'banana', french: 'banane', italian: 'banana', category: 'food', imagePrompt: 'yellow banana peeled, bunch of bananas, banana illustration for children' },
  { id: 'food_3', english: 'orange', french: 'orange', italian: 'arancia', category: 'food', imagePrompt: 'orange fruit sliced, citrus orange, orange illustration for children' },
  { id: 'food_4', english: 'strawberry', french: 'fraise', italian: 'fragola', category: 'food', imagePrompt: 'red strawberry with seeds, fresh strawberry, strawberry illustration for children' },
  { id: 'food_5', english: 'grapes', french: 'raisins', italian: 'uva', category: 'food', imagePrompt: 'purple grape bunch, cluster of grapes, grapes illustration for children' },
  { id: 'food_6', english: 'watermelon', french: 'pastèque', italian: 'anguria', category: 'food', imagePrompt: 'watermelon slice, red and green watermelon, watermelon illustration for children' },
  { id: 'food_7', english: 'bread', french: 'pain', italian: 'pane', category: 'food', imagePrompt: 'loaf of bread sliced, fresh bread, bread illustration for children' },
  { id: 'food_8', english: 'cheese', french: 'fromage', italian: 'formaggio', category: 'food', imagePrompt: 'cheese wedge with holes, yellow cheese, cheese illustration for children' },
  { id: 'food_9', english: 'milk', french: 'lait', italian: 'latte', category: 'food', imagePrompt: 'glass of milk, milk carton, milk illustration for children' },
  { id: 'food_10', english: 'egg', french: 'œuf', italian: 'uovo', category: 'food', imagePrompt: 'egg cracked open, fried egg, egg illustration for children' },
  { id: 'food_11', english: 'butter', french: 'beurre', italian: 'burro', category: 'food', imagePrompt: 'butter on dish, yellow butter, butter illustration for children' },
  { id: 'food_12', english: 'yogurt', french: 'yaourt', italian: 'yogurt', category: 'food', imagePrompt: 'yogurt cup with spoon, fruit yogurt, yogurt illustration for children' },
  { id: 'food_13', english: 'chicken', french: 'poulet', italian: 'pollo', category: 'food', imagePrompt: 'roasted chicken, chicken drumstick, chicken meal illustration for children' },
  { id: 'food_14', english: 'fish', french: 'poisson', italian: 'pesce', category: 'food', imagePrompt: 'cooked fish on plate, fish fillet, fish meal illustration for children' },
  { id: 'food_15', english: 'meat', french: 'viande', italian: 'carne', category: 'food', imagePrompt: 'steak on plate, meat cutlet, meat illustration for children' },
  { id: 'food_16', english: 'rice', french: 'riz', italian: 'riso', category: 'food', imagePrompt: 'bowl of white rice, steamed rice, rice illustration for children' },
  { id: 'food_17', english: 'pasta', french: 'pâtes', italian: 'pasta', category: 'food', imagePrompt: 'spaghetti on fork, pasta bowl, pasta illustration for children' },
  { id: 'food_18', english: 'pizza', french: 'pizza', italian: 'pizza', category: 'food', imagePrompt: 'pizza slice with toppings, whole pizza, pizza illustration for children' },
  { id: 'food_19', english: 'soup', french: 'soupe', italian: 'zuppa', category: 'food', imagePrompt: 'bowl of hot soup, steaming soup, soup illustration for children' },
  { id: 'food_20', english: 'salad', french: 'salade', italian: 'insalata', category: 'food', imagePrompt: 'green salad bowl, fresh vegetables, salad illustration for children' },
  { id: 'food_21', english: 'sandwich', french: 'sandwich', italian: 'panino', category: 'food', imagePrompt: 'sandwich with lettuce, club sandwich, sandwich illustration for children' },
  { id: 'food_22', english: 'hamburger', french: 'hamburger', italian: 'hamburger', category: 'food', imagePrompt: 'burger with bun, cheeseburger, hamburger illustration for children' },
  { id: 'food_23', english: 'hot dog', french: 'hot-dog', italian: 'hot dog', category: 'food', imagePrompt: 'hot dog in bun, sausage sandwich, hot dog illustration for children' },
  { id: 'food_24', english: 'french fries', french: 'frites', italian: 'patatine fritte', category: 'food', imagePrompt: 'golden french fries, fries in container, french fries illustration for children' },
  { id: 'food_25', english: 'ice cream', french: 'glace', italian: 'gelato', category: 'food', imagePrompt: 'ice cream cone, colorful ice cream, ice cream illustration for children' },
  { id: 'food_26', english: 'cake', french: 'gâteau', italian: 'torta', category: 'food', imagePrompt: 'birthday cake with candles, chocolate cake, cake illustration for children' },
  { id: 'food_27', english: 'cookie', french: 'biscuit', italian: 'biscotto', category: 'food', imagePrompt: 'chocolate chip cookie, cookie with bite, cookie illustration for children' },
  { id: 'food_28', english: 'chocolate', french: 'chocolat', italian: 'cioccolato', category: 'food', imagePrompt: 'chocolate bar squares, brown chocolate, chocolate illustration for children' },
  { id: 'food_29', english: 'candy', french: 'bonbon', italian: 'caramella', category: 'food', imagePrompt: 'wrapped candy, colorful sweets, candy illustration for children' },
  { id: 'food_30', english: 'water', french: 'eau', italian: 'acqua', category: 'food', imagePrompt: 'glass of water, water bottle, water illustration for children' },
  { id: 'food_31', english: 'juice', french: 'jus', italian: 'succo', category: 'food', imagePrompt: 'orange juice glass, fruit juice, juice illustration for children' },
  { id: 'food_32', english: 'tea', french: 'thé', italian: 'tè', category: 'food', imagePrompt: 'tea cup with steam, hot tea, tea illustration for children' },
  { id: 'food_33', english: 'coffee', french: 'café', italian: 'caffè', category: 'food', imagePrompt: 'coffee cup with steam, coffee mug, coffee illustration for children' },
  { id: 'food_34', english: 'sugar', french: 'sucre', italian: 'zucchero', category: 'food', imagePrompt: 'sugar cubes, spoonful of sugar, sugar illustration for children' },
  { id: 'food_35', english: 'salt', french: 'sel', italian: 'sale', category: 'food', imagePrompt: 'salt shaker, pinch of salt, salt illustration for children' },

  // Body Parts
  { id: 'body_1', english: 'head', french: 'tête', italian: 'testa', category: 'body', imagePrompt: 'human head profile, head with hair, head illustration for children' },
  { id: 'body_2', english: 'hair', french: 'cheveux', italian: 'capelli', category: 'body', imagePrompt: 'hair on head, different hairstyles, hair illustration for children' },
  { id: 'body_3', english: 'eye', french: 'œil', italian: 'occhio', category: 'body', imagePrompt: 'human eye with lashes, blue eye, eye illustration for children' },
  { id: 'body_4', english: 'ear', french: 'oreille', italian: 'orecchio', category: 'body', imagePrompt: 'human ear listening, ear shape, ear illustration for children' },
  { id: 'body_5', english: 'nose', french: 'nez', italian: 'naso', category: 'body', imagePrompt: 'human nose profile, nose smelling, nose illustration for children' },
  { id: 'body_6', english: 'mouth', french: 'bouche', italian: 'bocca', category: 'body', imagePrompt: 'smiling mouth, lips and teeth, mouth illustration for children' },
  { id: 'body_7', english: 'tooth', french: 'dent', italian: 'dente', category: 'body', imagePrompt: 'white tooth smiling, healthy tooth, tooth illustration for children' },
  { id: 'body_8', english: 'tongue', french: 'langue', italian: 'lingua', category: 'body', imagePrompt: 'tongue sticking out, pink tongue, tongue illustration for children' },
  { id: 'body_9', english: 'neck', french: 'cou', italian: 'collo', category: 'body', imagePrompt: 'human neck profile, neck and shoulders, neck illustration for children' },
  { id: 'body_10', english: 'shoulder', french: 'épaule', italian: 'spalla', category: 'body', imagePrompt: 'shoulder shrugging, shoulder joint, shoulder illustration for children' },
  { id: 'body_11', english: 'arm', french: 'bras', italian: 'braccio', category: 'body', imagePrompt: 'human arm flexing, arm with muscle, arm illustration for children' },
  { id: 'body_12', english: 'elbow', french: 'coude', italian: 'gomito', category: 'body', imagePrompt: 'bent elbow joint, elbow pointing, elbow illustration for children' },
  { id: 'body_13', english: 'hand', french: 'main', italian: 'mano', category: 'body', imagePrompt: 'open hand waving, hand with fingers, hand illustration for children' },
  { id: 'body_14', english: 'finger', french: 'doigt', italian: 'dito', category: 'body', imagePrompt: 'pointing finger, five fingers, finger illustration for children' },
  { id: 'body_15', english: 'chest', french: 'poitrine', italian: 'petto', category: 'body', imagePrompt: 'human chest torso, chest breathing, chest illustration for children' },
  { id: 'body_16', english: 'stomach', french: 'ventre', italian: 'pancia', category: 'body', imagePrompt: 'belly stomach area, tummy, stomach illustration for children' },
  { id: 'body_17', english: 'back', french: 'dos', italian: 'schiena', category: 'body', imagePrompt: 'human back view, back muscles, back illustration for children' },
  { id: 'body_18', english: 'leg', french: 'jambe', italian: 'gamba', category: 'body', imagePrompt: 'human leg standing, leg kicking, leg illustration for children' },
  { id: 'body_19', english: 'knee', french: 'genou', italian: 'ginocchio', category: 'body', imagePrompt: 'bent knee joint, knee cap, knee illustration for children' },
  { id: 'body_20', english: 'foot', french: 'pied', italian: 'piede', category: 'body', imagePrompt: 'human foot with toes, bare foot, foot illustration for children' },
  { id: 'body_21', english: 'toe', french: 'orteil', italian: 'dito del piede', category: 'body', imagePrompt: 'five toes wiggling, toe pointing, toe illustration for children' },

  // Colors
  { id: 'col_1', english: 'red', french: 'rouge', italian: 'rosso', category: 'colors', imagePrompt: 'red color swatch, red apple, red illustration for children' },
  { id: 'col_2', english: 'blue', french: 'bleu', italian: 'blu', category: 'colors', imagePrompt: 'blue color swatch, blue sky, blue illustration for children' },
  { id: 'col_3', english: 'yellow', french: 'jaune', italian: 'giallo', category: 'colors', imagePrompt: 'yellow color swatch, yellow sun, yellow illustration for children' },
  { id: 'col_4', english: 'green', french: 'vert', italian: 'verde', category: 'colors', imagePrompt: 'green color swatch, green leaf, green illustration for children' },
  { id: 'col_5', english: 'orange', french: 'orange', italian: 'arancione', category: 'colors', imagePrompt: 'orange color swatch, orange fruit, orange color illustration for children' },
  { id: 'col_6', english: 'purple', french: 'violet', italian: 'viola', category: 'colors', imagePrompt: 'purple color swatch, purple flower, purple illustration for children' },
  { id: 'col_7', english: 'pink', french: 'rose', italian: 'rosa', category: 'colors', imagePrompt: 'pink color swatch, pink flower, pink illustration for children' },
  { id: 'col_8', english: 'brown', french: 'brun', italian: 'marrone', category: 'colors', imagePrompt: 'brown color swatch, brown bear, brown illustration for children' },
  { id: 'col_9', english: 'black', french: 'noir', italian: 'nero', category: 'colors', imagePrompt: 'black color swatch, black cat, black illustration for children' },
  { id: 'col_10', english: 'white', french: 'blanc', italian: 'bianco', category: 'colors', imagePrompt: 'white color swatch, white cloud, white illustration for children' },
  { id: 'col_11', english: 'gray', french: 'gris', italian: 'grigio', category: 'colors', imagePrompt: 'gray color swatch, gray elephant, gray illustration for children' },

  // Clothing
  { id: 'cloth_1', english: 'shirt', french: 'chemise', italian: 'camicia', category: 'clothing', imagePrompt: 'button-up shirt, t-shirt, shirt illustration for children' },
  { id: 'cloth_2', english: 'pants', french: 'pantalon', italian: 'pantaloni', category: 'clothing', imagePrompt: 'blue jeans pants, trousers, pants illustration for children' },
  { id: 'cloth_3', english: 'dress', french: 'robe', italian: 'vestito', category: 'clothing', imagePrompt: 'pretty dress with flowers, sundress, dress illustration for children' },
  { id: 'cloth_4', english: 'skirt', french: 'jupe', italian: 'gonna', category: 'clothing', imagePrompt: 'pleated skirt, colorful skirt, skirt illustration for children' },
  { id: 'cloth_5', english: 'shoes', french: 'chaussures', italian: 'scarpe', category: 'clothing', imagePrompt: 'pair of shoes, sneakers, shoes illustration for children' },
  { id: 'cloth_6', english: 'socks', french: 'chaussettes', italian: 'calzini', category: 'clothing', imagePrompt: 'striped socks pair, colorful socks, socks illustration for children' },
  { id: 'cloth_7', english: 'hat', french: 'chapeau', italian: 'cappello', category: 'clothing', imagePrompt: 'baseball cap hat, sun hat, hat illustration for children' },
  { id: 'cloth_8', english: 'coat', french: 'manteau', italian: 'cappotto', category: 'clothing', imagePrompt: 'winter coat with buttons, jacket, coat illustration for children' },
  { id: 'cloth_9', english: 'jacket', french: 'veste', italian: 'giacca', category: 'clothing', imagePrompt: 'zipper jacket, denim jacket, jacket illustration for children' },
  { id: 'cloth_10', english: 'sweater', french: 'pull', italian: 'maglione', category: 'clothing', imagePrompt: 'knit sweater warm, pullover, sweater illustration for children' },
  { id: 'cloth_11', english: 'gloves', french: 'gants', italian: 'guanti', category: 'clothing', imagePrompt: 'winter gloves pair, mittens, gloves illustration for children' },
  { id: 'cloth_12', english: 'scarf', french: 'écharpe', italian: 'sciarpa', category: 'clothing', imagePrompt: 'striped scarf warm, winter scarf, scarf illustration for children' },
  { id: 'cloth_13', english: 'boots', french: 'bottes', italian: 'stivali', category: 'clothing', imagePrompt: 'rain boots, cowboy boots, boots illustration for children' },
  { id: 'cloth_14', english: 'belt', french: 'ceinture', italian: 'cintura', category: 'clothing', imagePrompt: 'leather belt with buckle, belt illustration for children' },
  { id: 'cloth_15', english: 'pajamas', french: 'pyjama', italian: 'pigiama', category: 'clothing', imagePrompt: 'sleeping pajamas set, nightwear, pajamas illustration for children' },

  // House & Rooms
  { id: 'house_1', english: 'house', french: 'maison', italian: 'casa', category: 'house', imagePrompt: 'cozy house with roof, home building, house illustration for children' },
  { id: 'house_2', english: 'door', french: 'porte', italian: 'porta', category: 'house', imagePrompt: 'wooden door with handle, entrance door, door illustration for children' },
  { id: 'house_3', english: 'window', french: 'fenêtre', italian: 'finestra', category: 'house', imagePrompt: 'window with curtains, glass window, window illustration for children' },
  { id: 'house_4', english: 'room', french: 'chambre', italian: 'stanza', category: 'house', imagePrompt: 'bedroom interior, living space, room illustration for children' },
  { id: 'house_5', english: 'kitchen', french: 'cuisine', italian: 'cucina', category: 'house', imagePrompt: 'kitchen with stove, cooking area, kitchen illustration for children' },
  { id: 'house_6', english: 'bathroom', french: 'salle de bain', italian: 'bagno', category: 'house', imagePrompt: 'bathroom with tub, washroom, bathroom illustration for children' },
  { id: 'house_7', english: 'bedroom', french: 'chambre à coucher', italian: 'camera da letto', category: 'house', imagePrompt: 'bedroom with bed, sleeping room, bedroom illustration for children' },
  { id: 'house_8', english: 'living room', french: 'salon', italian: 'soggiorno', category: 'house', imagePrompt: 'living room with sofa, family room, living room illustration for children' },
  { id: 'house_9', english: 'garden', french: 'jardin', italian: 'giardino', category: 'house', imagePrompt: 'garden with flowers, backyard, garden illustration for children' },
  { id: 'house_10', english: 'garage', french: 'garage', italian: 'garage', category: 'house', imagePrompt: 'garage with car, parking space, garage illustration for children' },
  { id: 'house_11', english: 'stairs', french: 'escaliers', italian: 'scale', category: 'house', imagePrompt: 'staircase going up, steps, stairs illustration for children' },
  { id: 'house_12', english: 'roof', french: 'toit', italian: 'tetto', category: 'house', imagePrompt: 'house roof with tiles, rooftop, roof illustration for children' },
  { id: 'house_13', english: 'wall', french: 'mur', italian: 'muro', category: 'house', imagePrompt: 'brick wall, painted wall, wall illustration for children' },
  { id: 'house_14', english: 'floor', french: 'sol', italian: 'pavimento', category: 'house', imagePrompt: 'wooden floor, carpet floor, floor illustration for children' },
  { id: 'house_15', english: 'ceiling', french: 'plafond', italian: 'soffitto', category: 'house', imagePrompt: 'room ceiling with light, ceiling fan, ceiling illustration for children' },

  // Furniture
  { id: 'furn_1', english: 'bed', french: 'lit', italian: 'letto', category: 'furniture', imagePrompt: 'bed with pillows, cozy bed, bed illustration for children' },
  { id: 'furn_2', english: 'chair', french: 'chaise', italian: 'sedia', category: 'furniture', imagePrompt: 'wooden chair, sitting chair, chair illustration for children' },
  { id: 'furn_3', english: 'table', french: 'table', italian: 'tavolo', category: 'furniture', imagePrompt: 'dining table, round table, table illustration for children' },
  { id: 'furn_4', english: 'sofa', french: 'canapé', italian: 'divano', category: 'furniture', imagePrompt: 'comfortable sofa, couch, sofa illustration for children' },
  { id: 'furn_5', english: 'desk', french: 'bureau', italian: 'scrivania', category: 'furniture', imagePrompt: 'study desk with drawer, work desk, desk illustration for children' },
  { id: 'furn_6', english: 'lamp', french: 'lampe', italian: 'lampada', category: 'furniture', imagePrompt: 'table lamp with shade, light lamp, lamp illustration for children' },
  { id: 'furn_7', english: 'mirror', french: 'miroir', italian: 'specchio', category: 'furniture', imagePrompt: 'wall mirror reflection, round mirror, mirror illustration for children' },
  { id: 'furn_8', english: 'closet', french: 'placard', italian: 'armadio', category: 'furniture', imagePrompt: 'closet with clothes, wardrobe, closet illustration for children' },
  { id: 'furn_9', english: 'drawer', french: 'tiroir', italian: 'cassetto', category: 'furniture', imagePrompt: 'drawer pulled open, chest drawer, drawer illustration for children' },
  { id: 'furn_10', english: 'shelf', french: 'étagère', italian: 'scaffale', category: 'furniture', imagePrompt: 'bookshelf with books, wall shelf, shelf illustration for children' },

  // Objects & Tools
  { id: 'obj_1', english: 'book', french: 'livre', italian: 'libro', category: 'objects', imagePrompt: 'open book with pages, storybook, book illustration for children' },
  { id: 'obj_2', english: 'pen', french: 'stylo', italian: 'penna', category: 'objects', imagePrompt: 'blue pen writing, ballpoint pen, pen illustration for children' },
  { id: 'obj_3', english: 'pencil', french: 'crayon', italian: 'matita', category: 'objects', imagePrompt: 'yellow pencil sharp, drawing pencil, pencil illustration for children' },
  { id: 'obj_4', english: 'paper', french: 'papier', italian: 'carta', category: 'objects', imagePrompt: 'white paper sheet, notebook paper, paper illustration for children' },
  { id: 'obj_5', english: 'scissors', french: 'ciseaux', italian: 'forbici', category: 'objects', imagePrompt: 'scissors cutting, safety scissors, scissors illustration for children' },
  { id: 'obj_6', english: 'bag', french: 'sac', italian: 'borsa', category: 'objects', imagePrompt: 'school bag backpack, shopping bag, bag illustration for children' },
  { id: 'obj_7', english: 'box', french: 'boîte', italian: 'scatola', category: 'objects', imagePrompt: 'cardboard box open, gift box, box illustration for children' },
  { id: 'obj_8', english: 'toy', french: 'jouet', italian: 'giocattolo', category: 'objects', imagePrompt: 'teddy bear toy, colorful toy, toy illustration for children' },
  { id: 'obj_9', english: 'ball', french: 'ballon', italian: 'palla', category: 'objects', imagePrompt: 'soccer ball round, bouncing ball, ball illustration for children' },
  { id: 'obj_10', english: 'doll', french: 'poupée', italian: 'bambola', category: 'objects', imagePrompt: 'baby doll with dress, toy doll, doll illustration for children' },
  { id: 'obj_11', english: 'phone', french: 'téléphone', italian: 'telefono', category: 'objects', imagePrompt: 'smartphone device, mobile phone, phone illustration for children' },
  { id: 'obj_12', english: 'computer', french: 'ordinateur', italian: 'computer', category: 'objects', imagePrompt: 'laptop computer screen, desktop PC, computer illustration for children' },
  { id: 'obj_13', english: 'television', french: 'télévision', italian: 'televisione', category: 'objects', imagePrompt: 'TV screen showing, flat television, TV illustration for children' },
  { id: 'obj_14', english: 'clock', french: 'horloge', italian: 'orologio', category: 'objects', imagePrompt: 'wall clock showing time, alarm clock, clock illustration for children' },
  { id: 'obj_15', english: 'key', french: 'clé', italian: 'chiave', category: 'objects', imagePrompt: 'door key metal, house key, key illustration for children' },
  { id: 'obj_16', english: 'money', french: 'argent', italian: 'soldi', category: 'objects', imagePrompt: 'coins and bills, paper money, money illustration for children' },
  { id: 'obj_17', english: 'glasses', french: 'lunettes', italian: 'occhiali', category: 'objects', imagePrompt: 'eyeglasses for reading, spectacles, glasses illustration for children' },
  { id: 'obj_18', english: 'umbrella', french: 'parapluie', italian: 'ombrello', category: 'objects', imagePrompt: 'open umbrella rain, colorful umbrella, umbrella illustration for children' },
  { id: 'obj_19', english: 'brush', french: 'brosse', italian: 'spazzola', category: 'objects', imagePrompt: 'hairbrush bristles, paint brush, brush illustration for children' },
  { id: 'obj_20', english: 'comb', french: 'peigne', italian: 'pettine', category: 'objects', imagePrompt: 'hair comb teeth, plastic comb, comb illustration for children' },

  // Kitchen Items
  { id: 'kit_1', english: 'plate', french: 'assiette', italian: 'piatto', category: 'kitchen', imagePrompt: 'dinner plate round, white plate, plate illustration for children' },
  { id: 'kit_2', english: 'cup', french: 'tasse', italian: 'tazza', category: 'kitchen', imagePrompt: 'tea cup with handle, coffee cup, cup illustration for children' },
  { id: 'kit_3', english: 'glass', french: 'verre', italian: 'bicchiere', category: 'kitchen', imagePrompt: 'drinking glass clear, water glass, glass illustration for children' },
  { id: 'kit_4', english: 'fork', french: 'fourchette', italian: 'forchetta', category: 'kitchen', imagePrompt: 'silver fork utensil, dinner fork, fork illustration for children' },
  { id: 'kit_5', english: 'knife', french: 'couteau', italian: 'coltello', category: 'kitchen', imagePrompt: 'butter knife safe, table knife, knife illustration for children' },
  { id: 'kit_6', english: 'spoon', french: 'cuillère', italian: 'cucchiaio', category: 'kitchen', imagePrompt: 'soup spoon silver, teaspoon, spoon illustration for children' },
  { id: 'kit_7', english: 'bowl', french: 'bol', italian: 'ciotola', category: 'kitchen', imagePrompt: 'cereal bowl round, soup bowl, bowl illustration for children' },
  { id: 'kit_8', english: 'pot', french: 'casserole', italian: 'pentola', category: 'kitchen', imagePrompt: 'cooking pot with lid, saucepan, pot illustration for children' },
  { id: 'kit_9', english: 'pan', french: 'poêle', italian: 'padella', category: 'kitchen', imagePrompt: 'frying pan with handle, skillet, pan illustration for children' },
  { id: 'kit_10', english: 'bottle', french: 'bouteille', italian: 'bottiglia', category: 'kitchen', imagePrompt: 'water bottle plastic, glass bottle, bottle illustration for children' },

  // Transportation
  { id: 'trans_1', english: 'car', french: 'voiture', italian: 'macchina', category: 'transport', imagePrompt: 'red car driving, automobile, car illustration for children' },
  { id: 'trans_2', english: 'bus', french: 'bus', italian: 'autobus', category: 'transport', imagePrompt: 'yellow school bus, city bus, bus illustration for children' },
  { id: 'trans_3', english: 'train', french: 'train', italian: 'treno', category: 'transport', imagePrompt: 'locomotive train tracks, passenger train, train illustration for children' },
  { id: 'trans_4', english: 'airplane', french: 'avion', italian: 'aereo', category: 'transport', imagePrompt: 'airplane flying clouds, jet plane, airplane illustration for children' },
  { id: 'trans_5', english: 'boat', french: 'bateau', italian: 'barca', category: 'transport', imagePrompt: 'sailing boat water, small boat, boat illustration for children' },
  { id: 'trans_6', english: 'bicycle', french: 'vélo', italian: 'bicicletta', category: 'transport', imagePrompt: 'bicycle with wheels, bike riding, bicycle illustration for children' },
  { id: 'trans_7', english: 'motorcycle', french: 'moto', italian: 'motocicletta', category: 'transport', imagePrompt: 'motorcycle racing, motorbike, motorcycle illustration for children' },
  { id: 'trans_8', english: 'truck', french: 'camion', italian: 'camion', category: 'transport', imagePrompt: 'big truck delivery, lorry, truck illustration for children' },
  { id: 'trans_9', english: 'helicopter', french: 'hélicoptère', italian: 'elicottero', category: 'transport', imagePrompt: 'helicopter flying rotor, chopper, helicopter illustration for children' },
  { id: 'trans_10', english: 'ship', french: 'navire', italian: 'nave', category: 'transport', imagePrompt: 'large ship sailing, cruise ship, ship illustration for children' },

  // Nature & Weather
  { id: 'nat_1', english: 'sun', french: 'soleil', italian: 'sole', category: 'nature', imagePrompt: 'bright sun shining, yellow sun rays, sun illustration for children' },
  { id: 'nat_2', english: 'moon', french: 'lune', italian: 'luna', category: 'nature', imagePrompt: 'crescent moon night, full moon, moon illustration for children' },
  { id: 'nat_3', english: 'star', french: 'étoile', italian: 'stella', category: 'nature', imagePrompt: 'twinkling star night, yellow star, star illustration for children' },
  { id: 'nat_4', english: 'cloud', french: 'nuage', italian: 'nuvola', category: 'nature', imagePrompt: 'fluffy white cloud, sky cloud, cloud illustration for children' },
  { id: 'nat_5', english: 'rain', french: 'pluie', italian: 'pioggia', category: 'nature', imagePrompt: 'rain drops falling, rainy weather, rain illustration for children' },
  { id: 'nat_6', english: 'snow', french: 'neige', italian: 'neve', category: 'nature', imagePrompt: 'snowflakes falling, white snow, snow illustration for children' },
  { id: 'nat_7', english: 'wind', french: 'vent', italian: 'vento', category: 'nature', imagePrompt: 'wind blowing leaves, breeze, wind illustration for children' },
  { id: 'nat_8', english: 'tree', french: 'arbre', italian: 'albero', category: 'nature', imagePrompt: 'green tree with leaves, oak tree, tree illustration for children' },
  { id: 'nat_9', english: 'flower', french: 'fleur', italian: 'fiore', category: 'nature', imagePrompt: 'colorful flower petals, blooming flower, flower illustration for children' },
  { id: 'nat_10', english: 'grass', french: 'herbe', italian: 'erba', category: 'nature', imagePrompt: 'green grass field, lawn grass, grass illustration for children' },
  { id: 'nat_11', english: 'leaf', french: 'feuille', italian: 'foglia', category: 'nature', imagePrompt: 'green leaf on branch, autumn leaf, leaf illustration for children' },
  { id: 'nat_12', english: 'mountain', french: 'montagne', italian: 'montagna', category: 'nature', imagePrompt: 'tall mountain peak, snowy mountain, mountain illustration for children' },
  { id: 'nat_13', english: 'river', french: 'rivière', italian: 'fiume', category: 'nature', imagePrompt: 'flowing river water, stream, river illustration for children' },
  { id: 'nat_14', english: 'sea', french: 'mer', italian: 'mare', category: 'nature', imagePrompt: 'ocean waves blue, seaside, sea illustration for children' },
  { id: 'nat_15', english: 'beach', french: 'plage', italian: 'spiaggia', category: 'nature', imagePrompt: 'sandy beach shore, beach umbrella, beach illustration for children' },
  { id: 'nat_16', english: 'forest', french: 'forêt', italian: 'foresta', category: 'nature', imagePrompt: 'dense forest trees, woodland, forest illustration for children' },
  { id: 'nat_17', english: 'sky', french: 'ciel', italian: 'cielo', category: 'nature', imagePrompt: 'blue sky clear, sky with clouds, sky illustration for children' },
  { id: 'nat_18', english: 'earth', french: 'terre', italian: 'terra', category: 'nature', imagePrompt: 'planet earth globe, world map, earth illustration for children' },
  { id: 'nat_19', english: 'fire', french: 'feu', italian: 'fuoco', category: 'nature', imagePrompt: 'campfire flames, orange fire, fire illustration for children' },
  { id: 'nat_20', english: 'water', french: 'eau', italian: 'acqua', category: 'nature', imagePrompt: 'water drops splash, clear water, water element illustration for children' },

  // Time & Days
  { id: 'time_1', english: 'day', french: 'jour', italian: 'giorno', category: 'time', imagePrompt: 'daytime sun bright, calendar day, day illustration for children' },
  { id: 'time_2', english: 'night', french: 'nuit', italian: 'notte', category: 'time', imagePrompt: 'nighttime moon stars, dark night, night illustration for children' },
  { id: 'time_3', english: 'morning', french: 'matin', italian: 'mattina', category: 'time', imagePrompt: 'sunrise morning, rooster crowing, morning illustration for children' },
  { id: 'time_4', english: 'afternoon', french: 'après-midi', italian: 'pomeriggio', category: 'time', imagePrompt: 'afternoon sun high, midday, afternoon illustration for children' },
  { id: 'time_5', english: 'evening', french: 'soir', italian: 'sera', category: 'time', imagePrompt: 'sunset evening, twilight, evening illustration for children' },
  { id: 'time_6', english: 'today', french: 'aujourd\'hui', italian: 'oggi', category: 'time', imagePrompt: 'calendar today marked, present day, today illustration for children' },
  { id: 'time_7', english: 'tomorrow', french: 'demain', italian: 'domani', category: 'time', imagePrompt: 'calendar next day, future arrow, tomorrow illustration for children' },
  { id: 'time_8', english: 'yesterday', french: 'hier', italian: 'ieri', category: 'time', imagePrompt: 'calendar previous day, past arrow, yesterday illustration for children' },
  { id: 'time_9', english: 'week', french: 'semaine', italian: 'settimana', category: 'time', imagePrompt: 'calendar week seven days, weekly planner, week illustration for children' },
  { id: 'time_10', english: 'month', french: 'mois', italian: 'mese', category: 'time', imagePrompt: 'calendar month page, monthly view, month illustration for children' },
  { id: 'time_11', english: 'year', french: 'an', italian: 'anno', category: 'time', imagePrompt: 'calendar full year, 12 months, year illustration for children' },
  { id: 'time_12', english: 'Monday', french: 'lundi', italian: 'lunedì', category: 'time', imagePrompt: 'Monday calendar, first weekday, Monday illustration for children' },
  { id: 'time_13', english: 'Tuesday', french: 'mardi', italian: 'martedì', category: 'time', imagePrompt: 'Tuesday calendar, second weekday, Tuesday illustration for children' },
  { id: 'time_14', english: 'Wednesday', french: 'mercredi', italian: 'mercoledì', category: 'time', imagePrompt: 'Wednesday calendar, midweek, Wednesday illustration for children' },
  { id: 'time_15', english: 'Thursday', french: 'jeudi', italian: 'giovedì', category: 'time', imagePrompt: 'Thursday calendar, fourth weekday, Thursday illustration for children' },
  { id: 'time_16', english: 'Friday', french: 'vendredi', italian: 'venerdì', category: 'time', imagePrompt: 'Friday calendar, weekend eve, Friday illustration for children' },
  { id: 'time_17', english: 'Saturday', french: 'samedi', italian: 'sabato', category: 'time', imagePrompt: 'Saturday calendar, weekend day, Saturday illustration for children' },
  { id: 'time_18', english: 'Sunday', french: 'dimanche', italian: 'domenica', category: 'time', imagePrompt: 'Sunday calendar, rest day, Sunday illustration for children' },

  // Actions/Verbs
  { id: 'act_1', english: 'eat', french: 'manger', italian: 'mangiare', category: 'actions', imagePrompt: 'child eating food, fork to mouth, eating illustration for children' },
  { id: 'act_2', english: 'drink', french: 'boire', italian: 'bere', category: 'actions', imagePrompt: 'drinking from cup, sipping water, drinking illustration for children' },
  { id: 'act_3', english: 'sleep', french: 'dormir', italian: 'dormire', category: 'actions', imagePrompt: 'sleeping in bed, closed eyes rest, sleeping illustration for children' },
  { id: 'act_4', english: 'run', french: 'courir', italian: 'correre', category: 'actions', imagePrompt: 'running fast motion, jogging exercise, running illustration for children' },
  { id: 'act_5', english: 'walk', french: 'marcher', italian: 'camminare', category: 'actions', imagePrompt: 'walking steps, strolling path, walking illustration for children' },
  { id: 'act_6', english: 'jump', french: 'sauter', italian: 'saltare', category: 'actions', imagePrompt: 'jumping up high, hopping motion, jumping illustration for children' },
  { id: 'act_7', english: 'sit', french: 's\'asseoir', italian: 'sedersi', category: 'actions', imagePrompt: 'sitting on chair, seated position, sitting illustration for children' },
  { id: 'act_8', english: 'stand', french: 'debout', italian: 'stare in piedi', category: 'actions', imagePrompt: 'standing upright, stand up straight, standing illustration for children' },
  { id: 'act_9', english: 'play', french: 'jouer', italian: 'giocare', category: 'actions', imagePrompt: 'playing with toys, fun games, playing illustration for children' },
  { id: 'act_10', english: 'read', french: 'lire', italian: 'leggere', category: 'actions', imagePrompt: 'reading book open, studying text, reading illustration for children' },
  { id: 'act_11', english: 'write', french: 'écrire', italian: 'scrivere', category: 'actions', imagePrompt: 'writing with pencil, making notes, writing illustration for children' },
  { id: 'act_12', english: 'draw', french: 'dessiner', italian: 'disegnare', category: 'actions', imagePrompt: 'drawing picture, art creation, drawing illustration for children' },
  { id: 'act_13', english: 'sing', french: 'chanter', italian: 'cantare', category: 'actions', imagePrompt: 'singing with microphone, musical notes, singing illustration for children' },
  { id: 'act_14', english: 'dance', french: 'danser', italian: 'ballare', category: 'actions', imagePrompt: 'dancing with music, ballet moves, dancing illustration for children' },
  { id: 'act_15', english: 'laugh', french: 'rire', italian: 'ridere', category: 'actions', imagePrompt: 'laughing happy face, giggling joy, laughing illustration for children' },
  { id: 'act_16', english: 'cry', french: 'pleurer', italian: 'piangere', category: 'actions', imagePrompt: 'crying tears sad, weeping emotion, crying illustration for children' },
  { id: 'act_17', english: 'speak', french: 'parler', italian: 'parlare', category: 'actions', imagePrompt: 'speaking mouth open, talking speech, speaking illustration for children' },
  { id: 'act_18', english: 'listen', french: 'écouter', italian: 'ascoltare', category: 'actions', imagePrompt: 'listening ear close, hearing sounds, listening illustration for children' },
  { id: 'act_19', english: 'look', french: 'regarder', italian: 'guardare', category: 'actions', imagePrompt: 'looking eyes open, watching observe, looking illustration for children' },
  { id: 'act_20', english: 'touch', french: 'toucher', italian: 'toccare', category: 'actions', imagePrompt: 'touching with finger, feeling texture, touching illustration for children' },
  { id: 'act_21', english: 'smell', french: 'sentir', italian: 'annusare', category: 'actions', imagePrompt: 'smelling flower nose, sniffing aroma, smelling illustration for children' },
  { id: 'act_22', english: 'taste', french: 'goûter', italian: 'assaggiare', category: 'actions', imagePrompt: 'tasting food tongue, trying flavor, tasting illustration for children' },
  { id: 'act_23', english: 'open', french: 'ouvrir', italian: 'aprire', category: 'actions', imagePrompt: 'opening door handle, open box, opening illustration for children' },
  { id: 'act_24', english: 'close', french: 'fermer', italian: 'chiudere', category: 'actions', imagePrompt: 'closing door shut, close window, closing illustration for children' },
  { id: 'act_25', english: 'give', french: 'donner', italian: 'dare', category: 'actions', imagePrompt: 'giving gift present, handing over, giving illustration for children' },
  { id: 'act_26', english: 'take', french: 'prendre', italian: 'prendere', category: 'actions', imagePrompt: 'taking object hand, grabbing item, taking illustration for children' },
  { id: 'act_27', english: 'come', french: 'venir', italian: 'venire', category: 'actions', imagePrompt: 'coming closer approach, arrive here, coming illustration for children' },
  { id: 'act_28', english: 'go', french: 'aller', italian: 'andare', category: 'actions', imagePrompt: 'going away leaving, depart move, going illustration for children' },
  { id: 'act_29', english: 'push', french: 'pousser', italian: 'spingere', category: 'actions', imagePrompt: 'pushing forward hands, push cart, pushing illustration for children' },
  { id: 'act_30', english: 'pull', french: 'tirer', italian: 'tirare', category: 'actions', imagePrompt: 'pulling rope back, tug wagon, pulling illustration for children' },

  // Emotions
  { id: 'emo_1', english: 'happy', french: 'heureux', italian: 'felice', category: 'emotions', imagePrompt: 'happy smiling face, joyful expression, happy illustration for children' },
  { id: 'emo_2', english: 'sad', french: 'triste', italian: 'triste', category: 'emotions', imagePrompt: 'sad frowning face, unhappy expression, sad illustration for children' },
  { id: 'emo_3', english: 'angry', french: 'en colère', italian: 'arrabbiato', category: 'emotions', imagePrompt: 'angry red face, mad expression, angry illustration for children' },
  { id: 'emo_4', english: 'scared', french: 'effrayé', italian: 'spaventato', category: 'emotions', imagePrompt: 'scared fearful face, frightened expression, scared illustration for children' },
  { id: 'emo_5', english: 'tired', french: 'fatigué', italian: 'stanco', category: 'emotions', imagePrompt: 'tired yawning face, sleepy expression, tired illustration for children' },
  { id: 'emo_6', english: 'excited', french: 'excité', italian: 'eccitato', category: 'emotions', imagePrompt: 'excited jumping joy, thrilled expression, excited illustration for children' },
  { id: 'emo_7', english: 'surprised', french: 'surpris', italian: 'sorpreso', category: 'emotions', imagePrompt: 'surprised open mouth, shocked expression, surprised illustration for children' },
  { id: 'emo_8', english: 'love', french: 'amour', italian: 'amore', category: 'emotions', imagePrompt: 'heart shape love, caring affection, love illustration for children' },

  // Expressions
  { id: 'expr_1', english: 'can I have', french: 'puis-je avoir', italian: 'posso avere', category: 'expressions', imagePrompt: 'child asking politely, requesting hand out, asking illustration for children' },
  { id: 'expr_2', english: 'I want', french: 'je veux', italian: 'voglio', category: 'expressions', imagePrompt: 'pointing at desired object, wanting gesture, desire illustration for children' },
  { id: 'expr_3', english: 'I like', french: 'j\'aime', italian: 'mi piace', category: 'expressions', imagePrompt: 'thumbs up approval, liking something, preference illustration for children' },
  { id: 'expr_4', english: 'I don\'t like', french: 'je n\'aime pas', italian: 'non mi piace', category: 'expressions', imagePrompt: 'thumbs down disapproval, dislike expression, rejection illustration for children' },
  { id: 'expr_5', english: 'I need', french: 'j\'ai besoin', italian: 'ho bisogno', category: 'expressions', imagePrompt: 'necessary requirement gesture, needing something, need illustration for children' },
  { id: 'expr_6', english: 'help me', french: 'aide-moi', italian: 'aiutami', category: 'expressions', imagePrompt: 'asking for help hand, assistance request, help illustration for children' },
  { id: 'expr_7', english: 'I\'m hungry', french: 'j\'ai faim', italian: 'ho fame', category: 'expressions', imagePrompt: 'rubbing tummy hungry, empty stomach, hunger illustration for children' },
  { id: 'expr_8', english: 'I\'m thirsty', french: 'j\'ai soif', italian: 'ho sete', category: 'expressions', imagePrompt: 'dry throat gesture, need water, thirst illustration for children' },
  { id: 'expr_9', english: 'I\'m cold', french: 'j\'ai froid', italian: 'ho freddo', category: 'expressions', imagePrompt: 'shivering cold arms, freezing temperature, cold illustration for children' },
  { id: 'expr_10', english: 'I\'m hot', french: 'j\'ai chaud', italian: 'ho caldo', category: 'expressions', imagePrompt: 'fanning face hot, sweating heat, warm illustration for children' },
  { id: 'expr_11', english: 'where is', french: 'où est', italian: 'dov\'è', category: 'expressions', imagePrompt: 'searching looking around, question location, where illustration for children' },
  { id: 'expr_12', english: 'what is this', french: 'qu\'est-ce que c\'est', italian: 'cos\'è questo', category: 'expressions', imagePrompt: 'pointing questioning object, curiosity gesture, what illustration for children' },
  { id: 'expr_13', english: 'how much', french: 'combien', italian: 'quanto', category: 'expressions', imagePrompt: 'counting fingers question, price inquiry, quantity illustration for children' },
  { id: 'expr_14', english: 'excuse me', french: 'excusez-moi', italian: 'scusi', category: 'expressions', imagePrompt: 'polite interruption gesture, attention seeking, excuse illustration for children' },
  { id: 'expr_15', english: 'I don\'t understand', french: 'je ne comprends pas', italian: 'non capisco', category: 'expressions', imagePrompt: 'confused shrug shoulders, puzzled expression, confusion illustration for children' },

  // School & Learning
  { id: 'sch_1', english: 'school', french: 'école', italian: 'scuola', category: 'school', imagePrompt: 'school building entrance, classroom setting, school illustration for children' },
  { id: 'sch_2', english: 'class', french: 'classe', italian: 'classe', category: 'school', imagePrompt: 'classroom with desks, students learning, class illustration for children' },
  { id: 'sch_3', english: 'student', french: 'élève', italian: 'studente', category: 'school', imagePrompt: 'student with backpack, child learning, pupil illustration for children' },
  { id: 'sch_4', english: 'homework', french: 'devoirs', italian: 'compiti', category: 'school', imagePrompt: 'homework on desk, assignments papers, homework illustration for children' },
  { id: 'sch_5', english: 'lesson', french: 'leçon', italian: 'lezione', category: 'school', imagePrompt: 'teacher teaching lesson, blackboard learning, lesson illustration for children' },
  { id: 'sch_6', english: 'alphabet', french: 'alphabet', italian: 'alfabeto', category: 'school', imagePrompt: 'ABC letters colorful, alphabet blocks, alphabet illustration for children' },
  { id: 'sch_7', english: 'number', french: 'nombre', italian: 'numero', category: 'school', imagePrompt: '123 numbers counting, mathematical digits, numbers illustration for children' },
  { id: 'sch_8', english: 'math', french: 'mathématiques', italian: 'matematica', category: 'school', imagePrompt: 'addition subtraction symbols, calculator numbers, math illustration for children' },
  { id: 'sch_9', english: 'science', french: 'sciences', italian: 'scienze', category: 'school', imagePrompt: 'science experiment flask, microscope lab, science illustration for children' },
  { id: 'sch_10', english: 'art', french: 'art', italian: 'arte', category: 'school', imagePrompt: 'painting palette brushes, creative artwork, art illustration for children' },

  // Seasons
  { id: 'seas_1', english: 'spring', french: 'printemps', italian: 'primavera', category: 'seasons', imagePrompt: 'spring flowers blooming, butterflies garden, spring illustration for children' },
  { id: 'seas_2', english: 'summer', french: 'été', italian: 'estate', category: 'seasons', imagePrompt: 'summer sun beach, ice cream vacation, summer illustration for children' },
  { id: 'seas_3', english: 'autumn', french: 'automne', italian: 'autunno', category: 'seasons', imagePrompt: 'autumn leaves falling, orange trees, fall illustration for children' },
  { id: 'seas_4', english: 'winter', french: 'hiver', italian: 'inverno', category: 'seasons', imagePrompt: 'winter snow snowman, cold weather, winter illustration for children' },

  // Sizes & Descriptions
  { id: 'size_1', english: 'big', french: 'grand', italian: 'grande', category: 'descriptions', imagePrompt: 'big elephant large, oversized object, big illustration for children' },
  { id: 'size_2', english: 'small', french: 'petit', italian: 'piccolo', category: 'descriptions', imagePrompt: 'small mouse tiny, miniature size, small illustration for children' },
  { id: 'size_3', english: 'tall', french: 'grand', italian: 'alto', category: 'descriptions', imagePrompt: 'tall giraffe height, skyscraper building, tall illustration for children' },
  { id: 'size_4', english: 'short', french: 'court', italian: 'corto', category: 'descriptions', imagePrompt: 'short height comparison, low stature, short illustration for children' },
  { id: 'size_5', english: 'long', french: 'long', italian: 'lungo', category: 'descriptions', imagePrompt: 'long snake stretched, extended length, long illustration for children' },
  { id: 'size_6', english: 'fast', french: 'rapide', italian: 'veloce', category: 'descriptions', imagePrompt: 'fast running cheetah, speed motion, fast illustration for children' },
  { id: 'size_7', english: 'slow', french: 'lent', italian: 'lento', category: 'descriptions', imagePrompt: 'slow turtle crawling, snail pace, slow illustration for children' },
  { id: 'size_8', english: 'hot', french: 'chaud', italian: 'caldo', category: 'descriptions', imagePrompt: 'hot sun fire, steam rising, hot illustration for children' },
  { id: 'size_9', english: 'cold', french: 'froid', italian: 'freddo', category: 'descriptions', imagePrompt: 'cold ice snow, freezing temperature, cold illustration for children' },
  { id: 'size_10', english: 'new', french: 'nouveau', italian: 'nuovo', category: 'descriptions', imagePrompt: 'new shiny toy, fresh unused, new illustration for children' },
  { id: 'size_11', english: 'old', french: 'vieux', italian: 'vecchio', category: 'descriptions', imagePrompt: 'old worn teddy, antique vintage, old illustration for children' },
  { id: 'size_12', english: 'good', french: 'bon', italian: 'buono', category: 'descriptions', imagePrompt: 'good thumbs up, positive checkmark, good illustration for children' },
  { id: 'size_13', english: 'bad', french: 'mauvais', italian: 'cattivo', category: 'descriptions', imagePrompt: 'bad thumbs down, negative cross, bad illustration for children' },
  { id: 'size_14', english: 'beautiful', french: 'beau', italian: 'bello', category: 'descriptions', imagePrompt: 'beautiful rainbow colors, pretty flowers, beautiful illustration for children' },
  { id: 'size_15', english: 'clean', french: 'propre', italian: 'pulito', category: 'descriptions', imagePrompt: 'clean sparkling surface, tidy room, clean illustration for children' },
  { id: 'size_16', english: 'dirty', french: 'sale', italian: 'sporco', category: 'descriptions', imagePrompt: 'dirty mud stains, messy hands, dirty illustration for children' },
  { id: 'size_17', english: 'easy', french: 'facile', italian: 'facile', category: 'descriptions', imagePrompt: 'easy simple puzzle, effortless task, easy illustration for children' },
  { id: 'size_18', english: 'difficult', french: 'difficile', italian: 'difficile', category: 'descriptions', imagePrompt: 'difficult complex maze, challenging puzzle, difficult illustration for children' },
  { id: 'size_19', english: 'full', french: 'plein', italian: 'pieno', category: 'descriptions', imagePrompt: 'full glass overflowing, complete filled, full illustration for children' },
  { id: 'size_20', english: 'empty', french: 'vide', italian: 'vuoto', category: 'descriptions', imagePrompt: 'empty container nothing, vacant space, empty illustration for children' }
];