import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import LockProtection from '@/components/LockProtection';
import ClientLayout from '@/components/ClientLayout';

const schoolbell = localFont({
  src: '../public/fonts/Twinkl-webfont.woff',
  variable: '--font-schoolbell',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={schoolbell.variable}>
        <LockProtection>
          <ClientLayout>
            {children}
          </ClientLayout>
        </LockProtection>
      </body>
    </html>
  );
}
