/**
 * Write down which words and sentences actually have an illustration.
 *
 * Generating the artwork is slow and rate-limited, so the data files run ahead
 * of the images for a while. Rather than hold the games back until the last
 * picture lands — or show her a broken frame as her reward for reading — each
 * game only offers the items whose illustration is on disk.
 *
 * Run this after a generation batch and commit the result:
 *   pnpm media:ready
 */
import * as fs from "node:fs";
import * as path from "node:path";

const root = process.cwd();

interface Target {
  /** Where the illustrations live. */
  images: string;
  /** The generated module to write. */
  out: string;
  exportName: string;
  what: string;
}

const TARGETS: Target[] = [
  {
    images: "public/images/sentences",
    out: "app/games/reading-sentences/ready.ts",
    exportName: "READY_SENTENCE_IDS",
    what: "sentences",
  },
  {
    images: "public/images/phonics",
    out: "app/games/phonics/ready.ts",
    exportName: "READY_WORD_IMAGES",
    what: "words",
  },
];

for (const target of TARGETS) {
  const dir = path.join(root, target.images);
  const ids = fs.existsSync(dir)
    ? fs
        .readdirSync(dir)
        .filter((file) => file.endsWith(".webp"))
        .map((file) => file.replace(/\.webp$/, ""))
        .sort()
    : [];

  const body = `// Generated by \`pnpm media:ready\` — do not edit by hand.
// The ${target.what} that have an illustration on disk. Anything missing is
// held back from the game until its picture has been generated.
export const ${target.exportName} = new Set<string>([
${ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")}
]);
`;

  fs.writeFileSync(path.join(root, target.out), body);
  console.log(`${target.out}: ${ids.length} ${target.what} ready`);
}
